export const LADDER_VERSION = '0.1.0';

export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Spanish' },
  { code: 'fr', label: 'French' },
  { code: 'de', label: 'German' },
  { code: 'ar', label: 'Arabic' },
  { code: 'hi', label: 'Hindi' },
  { code: 'ja', label: 'Japanese' },
  { code: 'ko', label: 'Korean' },
  { code: 'pt', label: 'Portuguese' },
  { code: 'zh', label: 'Chinese' },
  { code: 'custom', label: 'Custom' }
];

export const LADDER_TIERS = [
  {
    id: 'tier-01',
    name: 'Beginner',
    title: 'AI Orientation',
    accent: '#735f9e',
    vocabulary: ['artificial intelligence', 'machine learning', 'generative AI', 'model', 'chatbot', 'assistant', 'prompt', 'response', 'token', 'context', 'training data', 'inference', 'hallucination', 'multimodal', 'privacy'],
    topics: [
      'What artificial intelligence is and is not',
      'Traditional software vs AI systems',
      'Generative AI vs predictive AI',
      'Machine learning at a plain-language level',
      'Large language models at a plain-language level',
      'Chatbots, assistants, copilots, and agents',
      'Prompts, responses, and conversation turns',
      'Tokens and context windows',
      'Training data vs live information',
      'Hallucinations and why AI can be wrong',
      'AI strengths and weaknesses',
      'Common AI tool categories',
      'Multimodal AI basics',
      'Everyday AI use cases',
      'Basic privacy and sensitive data precautions',
      'Copyright and ownership awareness for beginners',
      'When not to use AI',
      'Beginner readiness check'
    ]
  },
  {
    id: 'tier-02',
    name: 'Novice',
    title: 'Prompting and Chatbot Fluency',
    accent: '#9a5fb0',
    vocabulary: ['system prompt', 'user prompt', 'role prompt', 'instruction', 'constraint', 'example', 'few-shot', 'output format', 'tone', 'persona', 'grounding', 'source', 'citation', 'follow-up', 'prompt template'],
    topics: [
      'Prompt anatomy',
      'Writing clear instructions',
      'Giving useful context',
      'Defining roles and personas',
      'Setting goals and success criteria',
      'Asking for specific output formats',
      'Using examples in prompts',
      'Prompt iteration and refinement',
      'Follow-up questions',
      'Asking AI to ask clarifying questions',
      'Asking for assumptions',
      'Asking for alternatives',
      'Asking for risks and tradeoffs',
      'Prompting for tone and audience',
      'Prompting for step-by-step help',
      'Prompting for checklists',
      'Prompting for critique and revision',
      'Novice readiness check'
    ]
  },
  {
    id: 'tier-03',
    name: 'Capable Learner',
    title: 'Research, Study, and Information Literacy',
    accent: '#c9a05a',
    vocabulary: ['source', 'primary source', 'secondary source', 'citation', 'claim', 'evidence', 'summary', 'synthesis', 'literature review', 'fact-checking', 'recency', 'credibility', 'bias', 'media literacy', 'epistemic humility'],
    topics: [
      'Using AI to learn unfamiliar topics',
      'Asking AI for learning plans',
      'Asking AI to explain at different difficulty levels',
      'Socratic tutoring with AI',
      'Generating practice questions',
      'Explaining mistakes with AI',
      'Summarizing articles and documents',
      'Comparing sources',
      'Identifying claims and evidence',
      'Fact-checking AI answers',
      'Understanding citation quality',
      'Using AI for research outlines',
      'Using AI for literature reviews',
      'Detecting weak or fabricated references',
      'Recognizing bias in AI responses',
      'Using AI with search engines',
      'Personal knowledge capture with AI',
      'Capable learner readiness check'
    ]
  },
  {
    id: 'tier-04',
    name: 'Knowledge Worker',
    title: 'Productivity and Professional Workflows',
    accent: '#3f7cac',
    vocabulary: ['workflow', 'SOP', 'template', 'knowledge base', 'meeting note', 'action item', 'task extraction', 'summarization', 'transformation', 'classification', 'prioritization', 'decision support', 'dashboard', 'review loop', 'human-in-the-loop'],
    topics: [
      'AI-assisted email drafting',
      'AI-assisted meeting notes',
      'AI-assisted action item extraction',
      'AI-assisted calendar and planning workflows',
      'AI-assisted document drafting',
      'AI-assisted document review',
      'AI-assisted spreadsheets',
      'AI-assisted data cleanup',
      'AI-assisted slide decks',
      'AI-assisted decision memos',
      'AI-assisted brainstorming',
      'AI-assisted project planning',
      'AI-assisted task prioritization',
      'AI-assisted personal productivity systems',
      'AI-assisted team communication',
      'Reusable prompt libraries',
      'Human review checkpoints',
      'Knowledge worker readiness check'
    ]
  },
  {
    id: 'tier-05',
    name: 'Creative User',
    title: 'Multimodal, Media, and Content Creation',
    accent: '#c0384f',
    vocabulary: ['multimodal', 'image generation', 'video generation', 'text-to-speech', 'speech-to-text', 'transcription', 'style transfer', 'storyboard', 'scene', 'prompt weighting', 'seed', 'upscaling', 'masking', 'inpainting', 'synthetic media'],
    topics: [
      'Image understanding with AI',
      'Image generation fundamentals',
      'Image editing and inpainting',
      'Brand-safe image generation',
      'Video generation fundamentals',
      'Video editing with AI',
      'Storyboarding with AI',
      'Audio transcription',
      'Voice generation and text-to-speech',
      'Music generation',
      'Podcast production with AI',
      'Social content workflows',
      'Marketing content workflows',
      'Design assistant workflows',
      'Presentation design with AI',
      'Synthetic media disclosure',
      'Deepfake awareness',
      'Creative user readiness check'
    ]
  },
  {
    id: 'tier-06',
    name: 'Business Practitioner',
    title: 'Function-Specific AI Use',
    accent: '#8a5cf6',
    vocabulary: ['use case', 'business process', 'ROI', 'customer journey', 'pipeline', 'segmentation', 'personalization', 'support ticket', 'knowledge article', 'HR screening', 'financial analysis', 'legal review', 'clinical decision support', 'domain risk', 'escalation'],
    topics: [
      'AI use-case discovery',
      'AI for marketing',
      'AI for sales',
      'AI for customer support',
      'AI for operations',
      'AI for finance and accounting',
      'AI for HR and recruiting',
      'AI for legal workflows',
      'AI for healthcare workflows',
      'AI for education workflows',
      'AI for nonprofits',
      'AI for small businesses',
      'AI for enterprise teams',
      'AI for ecommerce',
      'AI for real estate',
      'AI for government and civic services',
      'AI use-case risk screening',
      'Business practitioner readiness check'
    ]
  },
  {
    id: 'tier-07',
    name: 'Workflow Designer',
    title: 'No-Code, Automation, and Team Systems',
    accent: '#e6a817',
    vocabulary: ['automation', 'trigger', 'action', 'webhook', 'integration', 'connector', 'no-code', 'low-code', 'custom assistant', 'custom GPT', 'workspace', 'permission', 'audit trail', 'approval step', 'escalation path', 'workflow owner'],
    topics: [
      'Workflow mapping for AI automation',
      'Repeated-task identification',
      'SOP design for AI-assisted work',
      'No-code automation basics',
      'Low-code automation basics',
      'Trigger and action design',
      'Webhook literacy',
      'Custom assistant design',
      'Custom GPT design',
      'Knowledge upload patterns',
      'Team prompt libraries',
      'Workspace permissions',
      'Approval and review flows',
      'Escalation flows',
      'Audit trails for AI workflows',
      'Change management for AI workflows',
      'Automation failure modes',
      'Workflow designer readiness check'
    ]
  },
  {
    id: 'tier-08',
    name: 'Applied Builder',
    title: 'APIs, Structured Outputs, and AI App Basics',
    accent: '#6b7fd7',
    vocabulary: ['API', 'SDK', 'endpoint', 'request', 'response', 'JSON', 'schema', 'structured output', 'function calling', 'tool calling', 'streaming', 'latency', 'rate limit', 'token cost', 'model provider', 'environment variable'],
    topics: [
      'AI API fundamentals',
      'Model provider comparison',
      'API authentication',
      'Request and response structure',
      'Prompt variables in applications',
      'System and developer instructions',
      'Structured outputs',
      'JSON schema for AI responses',
      'Function calling basics',
      'Tool calling basics',
      'Streaming response UX',
      'File inputs',
      'Image inputs',
      'Audio inputs',
      'Cost estimation',
      'Latency management',
      'Basic AI application architecture',
      'Applied builder readiness check'
    ]
  },
  {
    id: 'tier-09',
    name: 'Knowledge Systems Builder',
    title: 'Data, Embeddings, Search, and RAG',
    accent: '#9a5fb0',
    vocabulary: ['embedding', 'vector', 'vector database', 'semantic search', 'keyword search', 'hybrid search', 'chunking', 'metadata', 'retrieval', 'reranking', 'RAG', 'grounding', 'citation', 'corpus', 'index', 'knowledge graph'],
    topics: [
      'Embeddings basics',
      'Vector search basics',
      'Vector database options',
      'Keyword search vs semantic search',
      'Hybrid search',
      'Document ingestion',
      'Chunking strategies',
      'Metadata design',
      'Retrieval-augmented generation',
      'Grounded answers',
      'Citation design',
      'Reranking',
      'Knowledge base design',
      'Knowledge graph integration',
      'Data freshness',
      'Retrieval evaluation',
      'Enterprise search architecture',
      'Knowledge systems builder readiness check'
    ]
  },
  {
    id: 'tier-10',
    name: 'Agent Builder',
    title: 'Agents, Tools, MCP, and Orchestration',
    accent: '#8a5cf6',
    vocabulary: ['agent', 'tool use', 'planning', 'orchestration', 'task loop', 'subagent', 'delegation', 'memory', 'state', 'trace', 'Model Context Protocol', 'MCP server', 'MCP client', 'tool permission', 'tool result', 'sandbox'],
    topics: [
      'Agent concepts',
      'AI workflow vs AI agent',
      'Tool-using agents',
      'Agent planning patterns',
      'Task decomposition',
      'State and memory',
      'Short-term memory patterns',
      'Long-term memory patterns',
      'Subagents',
      'Multi-agent coordination',
      'Agent orchestration frameworks',
      'Model Context Protocol basics',
      'MCP server design',
      'MCP client design',
      'Agent permissions',
      'Agent sandboxes',
      'Agent observability',
      'Agent builder readiness check'
    ]
  },
  {
    id: 'tier-11',
    name: 'AI Engineer',
    title: 'Evaluation, Reliability, Deployment, and Operations',
    accent: '#577590',
    vocabulary: ['eval', 'benchmark', 'golden dataset', 'test set', 'regression', 'LLM-as-judge', 'rubric', 'trace', 'observability', 'monitoring', 'fallback', 'cache', 'deployment', 'throughput', 'SLA', 'incident'],
    topics: [
      'Evaluation fundamentals',
      'Golden dataset creation',
      'LLM-as-judge evaluation',
      'Human evaluation workflows',
      'Rubric design',
      'Error analysis',
      'Prompt versioning',
      'Model comparison',
      'Regression testing for AI apps',
      'Trace analysis',
      'Observability tooling',
      'Monitoring production AI systems',
      'Fallback strategies',
      'Caching strategies',
      'Deployment patterns',
      'Incident response for AI systems',
      'AI system lifecycle management',
      'AI engineer readiness check'
    ]
  },
  {
    id: 'tier-12',
    name: 'AI Security Practitioner',
    title: 'Security, Privacy, Abuse, and Red Teaming',
    accent: '#d8572a',
    vocabulary: ['prompt injection', 'indirect prompt injection', 'jailbreak', 'data exfiltration', 'sensitive information disclosure', 'model theft', 'supply chain', 'sandbox escape', 'overreliance', 'excessive agency', 'adversarial example', 'red team', 'threat model', 'abuse monitoring'],
    topics: [
      'AI threat modeling',
      'Prompt injection',
      'Indirect prompt injection',
      'Jailbreaks',
      'Sensitive information disclosure',
      'Data exfiltration through tools',
      'Insecure output handling',
      'Tool permission risks',
      'Excessive agency',
      'Model denial of service and unbounded consumption',
      'Model theft and extraction',
      'Training data poisoning',
      'Vector and embedding weaknesses',
      'Supply chain risks in AI systems',
      'Red teaming AI applications',
      'Abuse monitoring',
      'Secure AI deployment checklists',
      'AI security practitioner readiness check'
    ]
  },
  {
    id: 'tier-13',
    name: 'AI Governance Practitioner',
    title: 'Law, Ethics, Policy, and Compliance',
    accent: '#2d6a4f',
    vocabulary: ['governance', 'ethics', 'responsible AI', 'transparency', 'explainability', 'fairness', 'bias', 'accountability', 'auditability', 'privacy', 'consent', 'copyright', 'intellectual property', 'high-risk AI', 'GPAI', 'AI management system'],
    topics: [
      'Responsible AI fundamentals',
      'AI ethics frameworks',
      'Bias and fairness',
      'Explainability and interpretability',
      'Transparency and disclosure',
      'Human oversight',
      'Privacy law basics for AI use',
      'Data protection and consent',
      'Copyright and training data',
      'AI-generated content ownership',
      'Workplace AI policy',
      'Education and academic integrity',
      'Vendor risk management',
      'NIST AI Risk Management Framework',
      'ISO/IEC 42001 AI management systems',
      'EU AI Act basics',
      'Sector-specific AI compliance',
      'AI governance practitioner readiness check'
    ]
  },
  {
    id: 'tier-14',
    name: 'AI Specialist',
    title: 'Model Science, ML, and Advanced AI Domains',
    accent: '#b08968',
    vocabulary: ['neural network', 'deep learning', 'transformer', 'attention', 'pretraining', 'post-training', 'fine-tuning', 'reinforcement learning', 'diffusion', 'classifier', 'recommender', 'time series', 'computer vision', 'speech model', 'robotics', 'MLOps'],
    topics: [
      'Machine learning fundamentals',
      'Supervised learning',
      'Unsupervised learning',
      'Deep learning fundamentals',
      'Transformer architecture',
      'Attention mechanisms',
      'Pretraining',
      'Post-training',
      'Fine-tuning',
      'Synthetic data',
      'Dataset quality',
      'Diffusion models',
      'Computer vision',
      'Speech AI',
      'Recommendation systems',
      'Forecasting and time series',
      'Reinforcement learning and robotics',
      'AI specialist readiness check'
    ]
  },
  {
    id: 'tier-15',
    name: 'AI Strategist',
    title: 'Product, Market, Adoption, and Frontier Planning',
    accent: '#735f9e',
    vocabulary: ['AI strategy', 'adoption roadmap', 'operating model', 'capability map', 'build vs buy', 'product moat', 'unit economics', 'adoption metric', 'change management', 'frontier model', 'alignment', 'interpretability', 'capability evaluation', 'regulatory monitoring', 'market map'],
    topics: [
      'AI strategy fundamentals',
      'AI opportunity discovery',
      'Use-case prioritization',
      'Build vs buy decisions',
      'AI vendor evaluation',
      'AI product management',
      'AI UX strategy',
      'AI business model design',
      'AI adoption roadmaps',
      'Team enablement programs',
      'Measuring AI adoption',
      'AI operating models',
      'AI market mapping',
      'Frontier AI capability tracking',
      'Interpretability and alignment awareness',
      'Regulatory monitoring',
      'Future-of-work planning',
      'AI strategist readiness check'
    ]
  }
].map((tier, tierIndex) => ({
  ...tier,
  order: tierIndex + 1,
  topics: tier.topics.map((title, topicIndex) => ({
    id: `T${String(tierIndex + 1).padStart(2, '0')}-L${String(topicIndex + 1).padStart(2, '0')}`,
    title,
    tierId: tier.id,
    order: topicIndex + 1
  }))
}));

export const DEFAULT_RESOURCES = [
  {
    type: 'official docs',
    label: 'OpenAI Agents Guide',
    url: 'https://platform.openai.com/docs/guides/agents',
    topicHints: ['agent', 'tool', 'orchestration', 'evaluation']
  },
  {
    type: 'official docs',
    label: 'Anthropic Model Context Protocol',
    url: 'https://docs.anthropic.com/en/docs/mcp',
    topicHints: ['MCP', 'tool', 'agent', 'context']
  },
  {
    type: 'official framework',
    label: 'NIST AI Risk Management Framework',
    url: 'https://www.nist.gov/itl/ai-risk-management-framework',
    topicHints: ['governance', 'risk', 'responsible', 'policy']
  },
  {
    type: 'official security',
    label: 'OWASP Top 10 for LLM Applications',
    url: 'https://owasp.org/www-project-top-10-for-large-language-model-applications/',
    topicHints: ['security', 'prompt injection', 'red team', 'abuse']
  },
  {
    type: 'official law',
    label: 'EU AI Act Overview',
    url: 'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai',
    topicHints: ['law', 'compliance', 'governance', 'EU AI Act']
  },
  {
    type: 'official course',
    label: 'Anthropic Academy',
    url: 'https://anthropic.skilljar.com/',
    topicHints: ['Claude', 'AI fluency', 'MCP', 'API']
  }
];
