export const LADDER_VERSION = '0.1.0';

export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Spanish' },
  { code: 'fr', label: 'French' },
  { code: 'de', label: 'German' },
  { code: 'ar', label: 'Arabic' },
  { code: 'hi', label: 'Hindi' },
  { code: 'ja', label: 'Japanese' },
  { code: 'ko', label: 'Korean' },
  { code: 'pt', label: 'Portuguese' },
  { code: 'zh-TW', label: 'Traditional Chinese' },
  { code: 'custom', label: 'Custom' }
];

export const LADDER_UI_TRANSLATIONS = {
  en: {
    // Ladder page - main UI
    howHighCanYouClimb: 'How high can you climb?',
    findARung: 'Find a Rung',
    searchTopicsOrCourses: 'Search topics or courses',
    certification: 'Certification',
    startCertification: 'Start certification',
    returnToTraining: 'Return to training',
    tierCertificationRibbons: 'Tier Certification Ribbons',
    authenticationRequired: 'Authentication Required',
    ladderCredentialExample: 'Ladder Credential Example',
    certificationGuide: 'Certification guide',
    howLadderCertificationWorks: 'How Ladder Certification Works',
    certificationExamInProgress: 'Certification exam in progress',
    admin: 'Admin',
    studentHub: 'Student Hub',
    backToCertification: 'Back to Certification',
    learnerIDInfo: 'Your Learner ID:',
    certificationsCompleted: 'Certifications completed',
    expertiseChallenges: 'Expertise challenges',
    masteryChallenges: 'Mastery challenges',
    tiersCertified: 'Tiers certified',
    certificationRecord: 'Certification record',
    noTopicsFound: 'No topics found. Try a different search.',
    selectEducationTier: 'Select education tier',
    selectMasteryLevel: 'Select mastery level',
    availableInDuration: 'Available in',
    adultAccountRequired: 'Adult account required',

    // Authenticate page - authentication flow
    completeYourAuthentication: 'Complete Your Authentication',
    verifyIdentityAndSetup: 'Verify your identity and set up your certification authentication before proceeding with advanced Ladder tiers.',
    accountSetup: 'Account Setup',
    identityAssurance: 'Identity Assurance',
    confirmation: 'Confirmation',
    adultTiersRequireAccount: 'Adult education tiers (Young Adult, College, Workforce, Leadership) require a verified account. Sign in to an existing account or create a new one.',
    emailUsername: 'Email / Username',
    password: 'Password',
    emailPlaceholder: 'name@example.com',
    passwordPlaceholder: 'Password',
    signIn: 'Sign in',
    createAccount: 'Create account',
    identityAssuranceLevel: 'Identity Assurance Level',
    proctoringMode: 'Proctoring Mode',
    chooseVerificationLevel: 'Choose verification level...',
    chooseProctoringMethod: 'Choose proctoring method...',
    selectVerificationLevel: 'Select how you want to verify your identity for this certification attempt. Different levels provide different assurance that the credential represents your work.',
    confirmIdentity: 'By proceeding, you confirm that you will take this certification attempt yourself and that any credential issued will represent your knowledge and skills.',
    confirmAttestion: 'I confirm that I am the person taking this certification attempt and that any credential issued will represent my work and knowledge.',
    returnToCertification: 'Return to Certification',
    cancel: 'Cancel',

    // Help text and tooltips
    findARungHelp: 'Search for topics or courses related to AI that interest you. You can start learning a topic or add it to your path without taking the assessment.',
    certificationHelp: 'Choose your education tier and mastery level, then take the certification assessment. Adult tiers require account authentication.',
    educationTierHelp: 'Select your education level: Student (K-12), Young Adult (18+), College, Workforce, or Leadership.',
    masteryLevelHelp: 'Choose your challenge level: Certification (basic competency), Expertise Challenge (advanced), or Mastery Challenge (expert-level synthesis).',
    identityAssuranceLevelHelp: 'Select your identity verification level: Self-attested (no check), Account-bound (tied to your account), Identity-attested (signed statement), or Proctored verified (ID + liveness + proctoring).'
  },
  es: {
    howHighCanYouClimb: '¿Qué tan alto puedes subir?',
    findARung: 'Encontrar un peldaño',
    searchTopicsOrCourses: 'Buscar temas o cursos',
    certification: 'Certificación',
    startCertification: 'Comenzar certificación',
    returnToTraining: 'Volver al entrenamiento',
    tierCertificationRibbons: 'Cintas de certificación de nivel',
    authenticationRequired: 'Autenticación requerida',
    ladderCredentialExample: 'Ejemplo de credencial de escalera',
    certificationGuide: 'Guía de certificación',
    howLadderCertificationWorks: 'Cómo funciona la certificación de escalera',
    certificationExamInProgress: 'Examen de certificación en progreso',
    admin: 'Admin',
    studentHub: 'Centro de estudiantes',
    backToCertification: 'Volver a certificación',
    learnerIDInfo: 'Tu ID de estudiante:',
    certificationsCompleted: 'Certificaciones completadas',
    expertiseChallenges: 'Desafíos de experiencia',
    masteryChallenges: 'Desafíos de maestría',
    tiersCertified: 'Niveles certificados',
    certificationRecord: 'Registro de certificación',
    noTopicsFound: 'No se encontraron temas. Intenta una búsqueda diferente.',
    selectEducationTier: 'Selecciona nivel de educación',
    selectMasteryLevel: 'Selecciona nivel de maestría',
    availableInDuration: 'Disponible en',
    adultAccountRequired: 'Cuenta de adulto requerida',
    completeYourAuthentication: 'Completa tu autenticación',
    verifyIdentityAndSetup: 'Verifica tu identidad y configura tu autenticación de certificación antes de continuar con los niveles avanzados de Ladder.',
    accountSetup: 'Configuración de cuenta',
    identityAssurance: 'Seguridad de identidad',
    confirmation: 'Confirmación',
    adultTiersRequireAccount: 'Los niveles de educación para adultos (Joven adulto, Colegio, Fuerza laboral, Liderazgo) requieren una cuenta verificada. Inicia sesión en una cuenta existente o crea una nueva.',
    emailUsername: 'Correo electrónico / Nombre de usuario',
    password: 'Contraseña',
    emailPlaceholder: 'nombre@ejemplo.com',
    passwordPlaceholder: 'Contraseña',
    signIn: 'Iniciar sesión',
    createAccount: 'Crear cuenta',
    identityAssuranceLevel: 'Nivel de seguridad de identidad',
    proctoringMode: 'Modo de proctoring',
    chooseVerificationLevel: 'Elige nivel de verificación...',
    chooseProctoringMethod: 'Elige método de proctoring...',
    selectVerificationLevel: 'Selecciona cómo deseas verificar tu identidad para este intento de certificación. Diferentes niveles proporcionan diferentes garantías de que la credencial representa tu trabajo.',
    confirmIdentity: 'Al continuar, confirmas que tomarás este intento de certificación tú mismo y que cualquier credencial emitida representará tu conocimiento y habilidades.',
    confirmAttestion: 'Confirmo que soy la persona que toma este intento de certificación y que cualquier credencial emitida representará mi trabajo y conocimiento.',
    returnToCertification: 'Volver a certificación',
    cancel: 'Cancelar',
    findARungHelp: 'Busca temas o cursos relacionados con IA que te interesen. Puedes comenzar a aprender un tema o agregarlo a tu ruta sin tomar la evaluación.',
    certificationHelp: 'Elige tu nivel de educación y nivel de maestría, luego realiza la evaluación de certificación. Los niveles para adultos requieren autenticación de cuenta.',
    educationTierHelp: 'Selecciona tu nivel de educación: Estudiante (K-12), Joven adulto (18+), Colegio, Fuerza laboral o Liderazgo.',
    masteryLevelHelp: 'Elige tu nivel de desafío: Certificación (competencia básica), Desafío de experiencia (avanzado) o Desafío de maestría (síntesis a nivel de experto).',
    identityAssuranceLevelHelp: 'Selecciona tu nivel de verificación de identidad: Auto-atestado (sin verificación), Vinculado a cuenta (vinculado a tu cuenta), Identidad atestada (declaración firmada) o Verificado por proctor (ID + liveness + proctoring).'
  },
  fr: {
    howHighCanYouClimb: 'Jusqu\'où peux-tu monter?',
    findARung: 'Trouver un échelon',
    searchTopicsOrCourses: 'Rechercher des sujets ou des cours',
    certification: 'Certification',
    startCertification: 'Commencer la certification',
    returnToTraining: 'Retour à la formation',
    tierCertificationRibbons: 'Rubans de certification de niveau',
    authenticationRequired: 'Authentification requise',
    ladderCredentialExample: 'Exemple de credential d\'échelle',
    certificationGuide: 'Guide de certification',
    howLadderCertificationWorks: 'Comment fonctionne la certification d\'échelle',
    certificationExamInProgress: 'Examen de certification en cours',
    admin: 'Admin',
    studentHub: 'Hub étudiant',
    backToCertification: 'Retour à la certification',
    learnerIDInfo: 'Ton ID d\'apprenant:',
    certificationsCompleted: 'Certifications complétées',
    expertiseChallenges: 'Défis d\'expertise',
    masteryChallenges: 'Défis de maîtrise',
    tiersCertified: 'Niveaux certifiés',
    certificationRecord: 'Dossier de certification',
    noTopicsFound: 'Aucun sujet trouvé. Essaie une recherche différente.',
    selectEducationTier: 'Sélectionner le niveau d\'éducation',
    selectMasteryLevel: 'Sélectionner le niveau de maîtrise',
    availableInDuration: 'Disponible dans',
    adultAccountRequired: 'Compte adulte requis',
    completeYourAuthentication: 'Complète ton authentification',
    verifyIdentityAndSetup: 'Vérifie ton identité et configure ton authentification de certification avant de continuer avec les niveaux avancés de Ladder.',
    accountSetup: 'Configuration du compte',
    identityAssurance: 'Assurance d\'identité',
    confirmation: 'Confirmation',
    adultTiersRequireAccount: 'Les niveaux d\'éducation pour adultes (Jeune adulte, Collège, Main-d\'œuvre, Leadership) nécessitent un compte vérifié. Connecte-toi à un compte existant ou crée-en un nouveau.',
    emailUsername: 'Email / Nom d\'utilisateur',
    password: 'Mot de passe',
    emailPlaceholder: 'nom@exemple.com',
    passwordPlaceholder: 'Mot de passe',
    signIn: 'Se connecter',
    createAccount: 'Créer un compte',
    identityAssuranceLevel: 'Niveau d\'assurance d\'identité',
    proctoringMode: 'Mode de surveillance',
    chooseVerificationLevel: 'Choisir le niveau de vérification...',
    chooseProctoringMethod: 'Choisir la méthode de surveillance...',
    selectVerificationLevel: 'Sélectionne comment tu veux vérifier ton identité pour cette tentative de certification. Différents niveaux fournissent différentes assurances que les credentials représentent ton travail.',
    confirmIdentity: 'En continuant, tu confirmes que tu participeras à cette tentative de certification toi-même et que toute credential émise représentera tes connaissances et compétences.',
    confirmAttestion: 'Je confirme que je suis la personne qui prend cette tentative de certification et que toute credential émise représentera mon travail et mes connaissances.',
    returnToCertification: 'Retour à la certification',
    cancel: 'Annuler',
    findARungHelp: 'Recherche des sujets ou des cours liés à l\'IA qui t\'intéressent. Tu peux commencer à apprendre un sujet ou l\'ajouter à ton chemin sans passer l\'évaluation.',
    certificationHelp: 'Choisissez votre niveau d\'éducation et votre niveau de maîtrise, puis passez l\'examen de certification. Les niveaux pour adultes nécessitent une authentification de compte.',
    educationTierHelp: 'Sélectionne ton niveau d\'éducation: Étudiant (K-12), Jeune adulte (18+), Collège, Main-d\'œuvre ou Leadership.',
    masteryLevelHelp: 'Choisis ton niveau de défi: Certification (compétence basique), Défi d\'expertise (avancé) ou Défi de maîtrise (synthèse au niveau expert).',
    identityAssuranceLevelHelp: 'Sélectionne ton niveau de vérification d\'identité: Auto-attesté (pas de vérification), Lié au compte (lié à ton compte), Identité attestée (déclaration signée) ou Vérifié par un surveillant (ID + vivacité + surveillance).'
  },
  de: {
    howHighCanYouClimb: 'Wie hoch kannst du klettern?',
    findARung: 'Eine Sprosse finden',
    searchTopicsOrCourses: 'Themen oder Kurse durchsuchen',
    certification: 'Zertifizierung',
    startCertification: 'Zertifizierung starten',
    returnToTraining: 'Zurück zum Training',
    tierCertificationRibbons: 'Tier-Zertifizierungsbänder',
    authenticationRequired: 'Authentifizierung erforderlich',
    ladderCredentialExample: 'Beispiel für Leiterberechtigungen',
    certificationGuide: 'Zertifizierungsleitfaden',
    howLadderCertificationWorks: 'So funktioniert die Leiterzertifizierung',
    certificationExamInProgress: 'Zertifizierungsprüfung läuft',
    admin: 'Admin',
    studentHub: 'Schülerzentrum',
    backToCertification: 'Zurück zur Zertifizierung',
    learnerIDInfo: 'Deine Lerner-ID:',
    certificationsCompleted: 'Zertifizierungen abgeschlossen',
    expertiseChallenges: 'Herausforderungen zur Expertise',
    masteryChallenges: 'Meisterschaftsherausforderungen',
    tiersCertified: 'Zertifizierte Stufen',
    certificationRecord: 'Zertifizierungseintrag',
    noTopicsFound: 'Keine Themen gefunden. Versuche eine andere Suche.',
    selectEducationTier: 'Bildungsstufe auswählen',
    selectMasteryLevel: 'Meisterschaftsgrad auswählen',
    availableInDuration: 'Verfügbar in',
    adultAccountRequired: 'Erwachsenenkonto erforderlich',
    completeYourAuthentication: 'Vervollständige deine Authentifizierung',
    verifyIdentityAndSetup: 'Überprüfe deine Identität und richte deine Zertifizierungsauthentifizierung ein, bevor du mit den erweiterten Leiter-Stufen fortfährst.',
    accountSetup: 'Kontoeinrichtung',
    identityAssurance: 'Identitätsgewährleistung',
    confirmation: 'Bestätigung',
    adultTiersRequireAccount: 'Erwachsenenbildungsstufen (Junger Erwachsener, Hochschule, Arbeitskraft, Führung) erfordern ein verifiziertes Konto. Melden dich bei einem bestehenden Konto an oder erstelle ein neues.',
    emailUsername: 'E-Mail / Benutzername',
    password: 'Passwort',
    emailPlaceholder: 'name@beispiel.de',
    passwordPlaceholder: 'Passwort',
    signIn: 'Anmelden',
    createAccount: 'Konto erstellen',
    identityAssuranceLevel: 'Identitätsgewährleistungsstufe',
    proctoringMode: 'Aufsichtsmodus',
    chooseVerificationLevel: 'Überprüfungsstufe wählen...',
    chooseProctoringMethod: 'Aufsichtsmethode wählen...',
    selectVerificationLevel: 'Wähle aus, wie du deine Identität für diesen Zertifizierungsversuch überprüfen möchtest. Unterschiedliche Stufen bieten unterschiedliche Gewährleistungen dafür, dass die Berechtigungsnachweise deine Arbeit darstellen.',
    confirmIdentity: 'Indem du fortfährst, bestätigst du, dass du diesen Zertifizierungsversuch selbst absolvierst und dass jede ausgegebene Berechtigung dein Wissen und deine Fähigkeiten darstellt.',
    confirmAttestion: 'Ich bestätige, dass ich die Person bin, die diesen Zertifizierungsversuch durchführt, und dass jede ausgegebene Berechtigung meine Arbeit und mein Wissen darstellt.',
    returnToCertification: 'Zurück zur Zertifizierung',
    cancel: 'Abbrechen',
    findARungHelp: 'Suche nach Themen oder Kursen zu KI, die dich interessieren. Du kannst mit einem Thema lernen beginnen oder es zu deinem Pfad hinzufügen, ohne die Bewertung abzulegen.',
    certificationHelp: 'Wähle deine Bildungsstufe und Meisterschaftsstufe, dann lege die Zertifizierungsbewertung ab. Erwachsenenstufen erfordern Kontententifizierung.',
    educationTierHelp: 'Wähle deine Bildungsstufe: Student (K-12), Junger Erwachsener (18+), Hochschule, Arbeitskraft oder Führung.',
    masteryLevelHelp: 'Wähle deine Herausforderungsstufe: Zertifizierung (grundlegende Kompetenz), Expertise-Herausforderung (fortgeschrittenes) oder Meisterschafts-Herausforderung (Expertensynthese).',
    identityAssuranceLevelHelp: 'Wähle deine Identitätsüberprüfungsstufe: Selbstbescheinigt (keine Überprüfung), Kontogebunden (an dein Konto gebunden), Identitätsbescheinigt (unterzeichnete Erklärung) oder Von Proktor verifiziert (ID + Liveness + Aufsicht).'
  },
  ar: {
    howHighCanYouClimb: 'إلى أي ارتفاع يمكنك الصعود؟',
    findARung: 'ابحث عن درجة',
    searchTopicsOrCourses: 'ابحث عن مواضيع أو دورات',
    certification: 'شهادة',
    startCertification: 'ابدأ الشهادة',
    returnToTraining: 'العودة إلى التدريب',
    tierCertificationRibbons: 'شرائط شهادة المستوى',
    authenticationRequired: 'المصادقة مطلوبة',
    ladderCredentialExample: 'مثال على بيانات سلم التدرج',
    certificationGuide: 'دليل الشهادة',
    howLadderCertificationWorks: 'كيف تعمل شهادة السلم',
    certificationExamInProgress: 'امتحان الشهادة قيد التنفيذ',
    admin: 'المسؤول',
    studentHub: 'مركز الطلاب',
    backToCertification: 'العودة إلى الشهادة',
    learnerIDInfo: 'معرف المتعلم الخاص بك:',
    certificationsCompleted: 'الشهادات المكتملة',
    expertiseChallenges: 'تحديات الخبرة',
    masteryChallenges: 'تحديات الإتقان',
    tiersCertified: 'مستويات معتمدة',
    certificationRecord: 'سجل الشهادة',
    noTopicsFound: 'لم يتم العثور على مواضيع. جرب بحثًا مختلفًا.',
    selectEducationTier: 'حدد المستوى التعليمي',
    selectMasteryLevel: 'حدد مستوى الإتقان',
    availableInDuration: 'متاح في',
    adultAccountRequired: 'حساب بالغ مطلوب',
    completeYourAuthentication: 'أكمل مصادقتك',
    verifyIdentityAndSetup: 'تحقق من هويتك وقم بإعداد مصادقة شهادتك قبل المتابعة مع مستويات Ladder المتقدمة.',
    accountSetup: 'إعداد الحساب',
    identityAssurance: 'ضمان الهوية',
    confirmation: 'تأكيد',
    adultTiersRequireAccount: 'مستويات التعليم للبالغين (الشاب البالغ، الكلية، القوى العاملة، القيادة) تتطلب حساباً معروفاً. قم بتسجيل الدخول إلى حساب موجود أو أنشئ حساباً جديداً.',
    emailUsername: 'البريد الإلكتروني / اسم المستخدم',
    password: 'كلمة المرور',
    emailPlaceholder: 'name@example.com',
    passwordPlaceholder: 'كلمة المرور',
    signIn: 'تسجيل الدخول',
    createAccount: 'إنشاء حساب',
    identityAssuranceLevel: 'مستوى ضمان الهوية',
    proctoringMode: 'وضع المراقبة',
    chooseVerificationLevel: 'اختر مستوى التحقق...',
    chooseProctoringMethod: 'اختر طريقة المراقبة...',
    selectVerificationLevel: 'حدد كيف تريد التحقق من هويتك لمحاولة الشهادة هذه. توفر المستويات المختلفة ضمانات مختلفة بأن بيانات الاعتماد تمثل عملك.',
    confirmIdentity: 'بالمتابعة، فإنك تؤكد أنك ستجري محاولة الشهادة هذه بنفسك وأن أي بيانات اعتماد صادرة ستمثل معرفتك ومهاراتك.',
    confirmAttestion: 'أؤكد أنني الشخص الذي يأخذ محاولة الشهادة هذه وأن أي بيانات اعتماد صادرة ستمثل عملي ومعرفتي.',
    returnToCertification: 'العودة إلى الشهادة',
    cancel: 'إلغاء',
    findARungHelp: 'ابحث عن مواضيع أو دورات تتعلق بالذكاء الاصطناعي تثير اهتمامك. يمكنك البدء في تعلم موضوع أو إضافته إلى مسارك دون إجراء التقييم.',
    certificationHelp: 'اختر مستوى التعليم الخاص بك ومستوى الإتقان، ثم أجرِ تقييم الشهادة. تتطلب المستويات البالغة مصادقة الحساب.',
    educationTierHelp: 'حدد مستوى التعليم الخاص بك: الطالب (K-12)، الشاب البالغ (18+)، الكلية، القوى العاملة أو القيادة.',
    masteryLevelHelp: 'اختر مستوى التحدي الخاص بك: الشهادة (الكفاءة الأساسية)، تحدي الخبرة (متقدم) أو تحدي الإتقان (تركيب على مستوى خبير).',
    identityAssuranceLevelHelp: 'حدد مستوى التحقق من الهوية الخاص بك: موثق ذاتياً (بدون تحقق)، مرتبط بالحساب (مرتبط بحسابك)، هوية موثقة (بيان موقع) أو تم التحقق منه بواسطة المشرف (معرف + حيوية + مراقبة).'
  },
  hi: {
    howHighCanYouClimb: 'आप कितना ऊंचा चढ़ सकते हैं?',
    findARung: 'एक रंग खोजें',
    searchTopicsOrCourses: 'विषयों या पाठ्यक्रमों को खोजें',
    certification: 'प्रमाणन',
    startCertification: 'प्रमाणन शुरू करें',
    returnToTraining: 'प्रशिक्षण पर लौटें',
    tierCertificationRibbons: 'स्तर प्रमाणन रिबन',
    authenticationRequired: 'प्रमाणीकरण आवश्यक है',
    ladderCredentialExample: 'सीढ़ी क्रेडेंशियल उदाहरण',
    certificationGuide: 'प्रमाणन मार्गदर्शिका',
    howLadderCertificationWorks: 'सीढ़ी प्रमाणन कैसे काम करता है',
    certificationExamInProgress: 'प्रमाणन परीक्षा चल रही है',
    admin: 'प्रशासक',
    studentHub: 'छात्र केंद्र',
    backToCertification: 'प्रमाणन पर लौटें',
    learnerIDInfo: 'आपकी शिक्षार्थी ID:',
    certificationsCompleted: 'पूर्ण प्रमाणन',
    expertiseChallenges: 'विशेषज्ञता चुनौतियाँ',
    masteryChallenges: 'महारत चुनौतियाँ',
    tiersCertified: 'स्तर प्रमाणित',
    certificationRecord: 'प्रमाणन रिकॉर्ड',
    noTopicsFound: 'कोई विषय नहीं मिला। एक अलग खोज का प्रयास करें।',
    selectEducationTier: 'शिक्षा स्तर चुनें',
    selectMasteryLevel: 'महारत स्तर चुनें',
    availableInDuration: 'में उपलब्ध',
    adultAccountRequired: 'वयस्क खाता आवश्यक है',
    completeYourAuthentication: 'अपना प्रमाणीकरण पूरा करें',
    verifyIdentityAndSetup: 'Ladder के उन्नत स्तरों के साथ आगे बढ़ने से पहले अपनी पहचान सत्यापित करें और अपनी प्रमाणन प्रमाणीकरण स्थापित करें।',
    accountSetup: 'खाता सेटअप',
    identityAssurance: 'पहचान आश्वासन',
    confirmation: 'पुष्टि',
    adultTiersRequireAccount: 'वयस्क शिक्षा स्तर (युवा वयस्क, कॉलेज, कार्यबल, नेतृत्व) को सत्यापित खाते की आवश्यकता है। किसी मौजूदा खाते में साइन इन करें या एक नया खाता बनाएं।',
    emailUsername: 'ईमेल / उपयोगकर्ता नाम',
    password: 'पासवर्ड',
    emailPlaceholder: 'name@example.com',
    passwordPlaceholder: 'पासवर्ड',
    signIn: 'साइन इन करें',
    createAccount: 'खाता बनाएं',
    identityAssuranceLevel: 'पहचान आश्वासन स्तर',
    proctoringMode: 'निगरानी मोड',
    chooseVerificationLevel: 'सत्यापन स्तर चुनें...',
    chooseProctoringMethod: 'निगरानी विधि चुनें...',
    selectVerificationLevel: 'इस प्रमाणन प्रयास के लिए अपनी पहचान सत्यापित करने का तरीका चुनें। विभिन्न स्तर अलग-अलग आश्वासन प्रदान करते हैं कि क्रेडेंशियल आपके काम का प्रतिनिधित्व करता है।',
    confirmIdentity: 'आगे बढ़ते हुए, आप पुष्टि करते हैं कि आप यह प्रमाणन प्रयास स्वयं लेंगे और जारी किया गया कोई भी क्रेडेंशियल आपके ज्ञान और कौशल का प्रतिनिधित्व करेगा।',
    confirmAttestion: 'मैं पुष्टि करता हूँ कि मैं यह प्रमाणन प्रयास लेने वाला व्यक्ति हूँ और कोई भी जारी क्रेडेंशियल मेरे काम और ज्ञान का प्रतिनिधित्व करेगा।',
    returnToCertification: 'प्रमाणन पर लौटें',
    cancel: 'रद्द करें',
    findARungHelp: 'AI से संबंधित विषयों या पाठ्यक्रमों को खोजें जो आपकी रुचि रखते हों। आप मूल्यांकन लिए बिना किसी विषय को सीखना शुरू कर सकते हैं या इसे अपने पथ में जोड़ सकते हैं।',
    certificationHelp: 'अपना शिक्षा स्तर और महारत स्तर चुनें, फिर प्रमाणन मूल्यांकन लें। वयस्क स्तरों के लिए खाता प्रमाणीकरण की आवश्यकता है।',
    educationTierHelp: 'अपना शिक्षा स्तर चुनें: छात्र (K-12), युवा वयस्क (18+), कॉलेज, कार्यबल या नेतृत्व।',
    masteryLevelHelp: 'अपना चुनौती स्तर चुनें: प्रमाणन (मूल दक्षता), विशेषज्ञता चुनौती (उन्नत) या महारत चुनौती (विशेषज्ञ-स्तरीय संश्लेषण)।',
    identityAssuranceLevelHelp: 'अपना पहचान सत्यापन स्तर चुनें: स्व-प्रमाणित (कोई जाँच नहीं), खाता-बाउंड (आपके खाते से जुड़ा), पहचान-प्रमाणित (हस्ताक्षरित बयान) या निगरानीकर्ता द्वारा सत्यापित (ID + liveness + निगरानी)।'
  },
  ja: {
    howHighCanYouClimb: 'どこまで登れますか?',
    findARung: 'ステップを見つける',
    searchTopicsOrCourses: 'トピックまたはコースを検索',
    certification: '認定',
    startCertification: '認定を開始',
    returnToTraining: 'トレーニングに戻る',
    tierCertificationRibbons: 'レベル認定リボン',
    authenticationRequired: '認証が必要です',
    ladderCredentialExample: 'ラダー資格情報の例',
    certificationGuide: '認定ガイド',
    howLadderCertificationWorks: 'ラダー認定の仕組み',
    certificationExamInProgress: '認定試験が進行中',
    admin: '管理者',
    studentHub: '学生ハブ',
    backToCertification: '認定に戻る',
    learnerIDInfo: 'あなたの学習者ID:',
    certificationsCompleted: '完了した認定',
    expertiseChallenges: '専門知識チャレンジ',
    masteryChallenges: 'マスタリーチャレンジ',
    tiersCertified: '認定レベル',
    certificationRecord: '認定記録',
    noTopicsFound: 'トピックが見つかりません。別の検索を試してください。',
    selectEducationTier: '教育レベルを選択',
    selectMasteryLevel: 'マスタリーレベルを選択',
    availableInDuration: 'で利用可能',
    adultAccountRequired: '成人アカウントが必要です',
    completeYourAuthentication: '認証を完了してください',
    verifyIdentityAndSetup: 'ラダーの高度なレベルに進む前に、身元を確認し、認定認証をセットアップしてください。',
    accountSetup: 'アカウントセットアップ',
    identityAssurance: '身元の確認',
    confirmation: '確認',
    adultTiersRequireAccount: '成人教育レベル(青年、大学、職場、リーダーシップ)は確認済みアカウントが必要です。既存のアカウントにサインインするか、新しいアカウントを作成してください。',
    emailUsername: 'メール / ユーザー名',
    password: 'パスワード',
    emailPlaceholder: 'name@example.com',
    passwordPlaceholder: 'パスワード',
    signIn: 'サインイン',
    createAccount: 'アカウント作成',
    identityAssuranceLevel: '身元確認レベル',
    proctoringMode: 'プロクタリングモード',
    chooseVerificationLevel: '検証レベルを選択...',
    chooseProctoringMethod: 'プロクタリング方法を選択...',
    selectVerificationLevel: 'この認定試験で身元を確認する方法を選択してください。異なるレベルは、資格情報があなたの作品を表すことに対して異なる保証を提供します。',
    confirmIdentity: '先に進むことで、あなたはこの認定試験に自分で参加し、発行された資格情報があなたの知識とスキルを表すことを確認します。',
    confirmAttestion: 'この認定試験に参加している人物が自分であること、および発行される資格情報が自分の作品と知識を表すことを確認します。',
    returnToCertification: '認定に戻る',
    cancel: 'キャンセル',
    findARungHelp: 'あなたに興味のあるAI関連のトピックやコースを検索します。評価を受けずにトピックを学び始めたり、パスに追加したりできます。',
    certificationHelp: '教育レベルとマスタリーレベルを選択してから、認定評価を受けてください。成人レベルはアカウント認証が必要です。',
    educationTierHelp: '教育レベルを選択してください:学生(K-12)、青年(18+)、大学、職場、またはリーダーシップ。',
    masteryLevelHelp: 'チャレンジレベルを選択してください:認定(基本的な能力)、専門知識チャレンジ(上級)、またはマスタリーチャレンジ(専門家レベルの総合)。',
    identityAssuranceLevelHelp: '身元確認レベルを選択してください:自己認証(チェックなし)、アカウント所有者(あなたのアカウントに結び付けられている)、身元認証(署名済みステートメント)、またはプロクターによって確認(ID +生存性+プロクタリング)。'
  },
  ko: {
    howHighCanYouClimb: '당신은 얼마나 높이 올라갈 수 있습니까?',
    findARung: '계단 찾기',
    searchTopicsOrCourses: '주제 또는 코스 검색',
    certification: '인증',
    startCertification: '인증 시작',
    returnToTraining: '교육으로 돌아가기',
    tierCertificationRibbons: '레벨 인증 리본',
    authenticationRequired: '인증 필요',
    ladderCredentialExample: '사다리 자격증 예시',
    certificationGuide: '인증 가이드',
    howLadderCertificationWorks: '사다리 인증의 작동 방식',
    certificationExamInProgress: '인증 시험 진행 중',
    admin: '관리자',
    studentHub: '학생 허브',
    backToCertification: '인증으로 돌아가기',
    learnerIDInfo: '당신의 학습자 ID:',
    certificationsCompleted: '완료된 인증',
    expertiseChallenges: '전문성 도전',
    masteryChallenges: '마스터리 도전',
    tiersCertified: '인증 레벨',
    certificationRecord: '인증 기록',
    noTopicsFound: '주제를 찾을 수 없습니다. 다른 검색을 시도하십시오.',
    selectEducationTier: '교육 레벨 선택',
    selectMasteryLevel: '마스터리 레벨 선택',
    availableInDuration: '내에 이용 가능',
    adultAccountRequired: '성인 계정 필요',
    completeYourAuthentication: '인증을 완료하세요',
    verifyIdentityAndSetup: '사다리의 고급 레벨로 진행하기 전에 신원을 확인하고 인증 인증을 설정하세요.',
    accountSetup: '계정 설정',
    identityAssurance: '신원 보증',
    confirmation: '확인',
    adultTiersRequireAccount: '성인 교육 레벨(청년, 대학, 직장, 리더십)은 확인된 계정이 필요합니다. 기존 계정에 로그인하거나 새 계정을 만드세요.',
    emailUsername: '이메일 / 사용자 이름',
    password: '비밀번호',
    emailPlaceholder: 'name@example.com',
    passwordPlaceholder: '비밀번호',
    signIn: '로그인',
    createAccount: '계정 만들기',
    identityAssuranceLevel: '신원 보증 레벨',
    proctoringMode: '감시 모드',
    chooseVerificationLevel: '검증 레벨 선택...',
    chooseProctoringMethod: '감시 방법 선택...',
    selectVerificationLevel: '이 인증 시도에 대해 신원을 확인하는 방법을 선택하세요. 다양한 레벨은 자격증이 당신의 작업을 나타내는 것에 대한 다양한 보증을 제공합니다.',
    confirmIdentity: '진행하면 이 인증 시도를 직접 수행하고 발급된 자격증이 당신의 지식과 기술을 나타낼 것임을 확인합니다.',
    confirmAttestion: '이 인증 시도를 수행하는 사람이 나 자신이며 발급된 자격증이 내 작업과 지식을 나타낼 것임을 확인합니다.',
    returnToCertification: '인증으로 돌아가기',
    cancel: '취소',
    findARungHelp: '당신에게 관심있는 AI 관련 주제 또는 코스를 검색하세요. 평가를 받지 않고 주제를 배우기 시작하거나 경로에 추가할 수 있습니다.',
    certificationHelp: '교육 레벨과 마스터리 레벨을 선택한 후 인증 평가를 받으세요. 성인 레벨은 계정 인증이 필요합니다.',
    educationTierHelp: '교육 레벨을 선택하세요: 학생(K-12), 청년(18+), 대학, 직장 또는 리더십.',
    masteryLevelHelp: '도전 레벨을 선택하세요: 인증(기본 역량), 전문성 도전(고급) 또는 마스터리 도전(전문가 수준 종합).',
    identityAssuranceLevelHelp: '신원 검증 레벨을 선택하세요: 자가 증명(확인 없음), 계정 바운드(계정에 연결), 신원 증명(서명된 진술) 또는 감시자 검증(ID + 생생함 + 감시).'
  },
  pt: {
    howHighCanYouClimb: 'Até que altura você consegue subir?',
    findARung: 'Encontre um degrau',
    searchTopicsOrCourses: 'Pesquisar tópicos ou cursos',
    certification: 'Certificação',
    startCertification: 'Iniciar certificação',
    returnToTraining: 'Voltar ao treinamento',
    tierCertificationRibbons: 'Fitas de certificação de nível',
    authenticationRequired: 'Autenticação necessária',
    ladderCredentialExample: 'Exemplo de credencial de escada',
    certificationGuide: 'Guia de certificação',
    howLadderCertificationWorks: 'Como funciona a certificação de escada',
    certificationExamInProgress: 'Exame de certificação em progresso',
    admin: 'Admin',
    studentHub: 'Centro do aluno',
    backToCertification: 'Voltar à certificação',
    learnerIDInfo: 'Seu ID de aluno:',
    certificationsCompleted: 'Certificações concluídas',
    expertiseChallenges: 'Desafios de especialização',
    masteryChallenges: 'Desafios de maestria',
    tiersCertified: 'Níveis certificados',
    certificationRecord: 'Registro de certificação',
    noTopicsFound: 'Nenhum tópico encontrado. Tente uma pesquisa diferente.',
    selectEducationTier: 'Selecione nível de educação',
    selectMasteryLevel: 'Selecione nível de maestria',
    availableInDuration: 'Disponível em',
    adultAccountRequired: 'Conta de adulto necessária',
    completeYourAuthentication: 'Complete sua autenticação',
    verifyIdentityAndSetup: 'Verifique sua identidade e configure sua autenticação de certificação antes de prosseguir com níveis avançados de Ladder.',
    accountSetup: 'Configuração de conta',
    identityAssurance: 'Garantia de identidade',
    confirmation: 'Confirmação',
    adultTiersRequireAccount: 'Os níveis de educação para adultos (Jovem adulto, Faculdade, Força de trabalho, Liderança) exigem uma conta verificada. Faça login em uma conta existente ou crie uma nova.',
    emailUsername: 'Email / Nome de usuário',
    password: 'Senha',
    emailPlaceholder: 'nome@exemplo.com',
    passwordPlaceholder: 'Senha',
    signIn: 'Fazer login',
    createAccount: 'Criar conta',
    identityAssuranceLevel: 'Nível de garantia de identidade',
    proctoringMode: 'Modo de proctoria',
    chooseVerificationLevel: 'Escolha o nível de verificação...',
    chooseProctoringMethod: 'Escolha o método de proctoria...',
    selectVerificationLevel: 'Selecione como deseja verificar sua identidade para esta tentativa de certificação. Diferentes níveis fornecem diferentes garantias de que a credencial representa seu trabalho.',
    confirmIdentity: 'Ao prosseguir, você confirma que realizará esta tentativa de certificação pessoalmente e que qualquer credencial emitida representará seu conhecimento e habilidades.',
    confirmAttestion: 'Confirmo que sou a pessoa realizando esta tentativa de certificação e que qualquer credencial emitida representará meu trabalho e conhecimento.',
    returnToCertification: 'Voltar à certificação',
    cancel: 'Cancelar',
    findARungHelp: 'Pesquise tópicos ou cursos relacionados à IA que o interessem. Você pode começar a aprender um tópico ou adicioná-lo ao seu caminho sem fazer a avaliação.',
    certificationHelp: 'Escolha seu nível de educação e nível de maestria, depois faça a avaliação de certificação. Os níveis para adultos exigem autenticação de conta.',
    educationTierHelp: 'Selecione seu nível de educação: Aluno (K-12), Jovem adulto (18+), Faculdade, Força de trabalho ou Liderança.',
    masteryLevelHelp: 'Escolha seu nível de desafio: Certificação (competência básica), Desafio de especialização (avançado) ou Desafio de maestria (síntese em nível de especialista).',
    identityAssuranceLevelHelp: 'Selecione seu nível de verificação de identidade: Auto-atestado (sem verificação), Vinculado a conta (vinculado à sua conta), Identidade atestada (declaração assinada) ou Verificado por proctor (ID + vivacidade + proctoria).'
  },
  'zh-TW': {
    howHighCanYouClimb: '你能爬多高？',
    findARung: '找一個梯級',
    searchTopicsOrCourses: '搜尋主題或課程',
    certification: '認證',
    startCertification: '開始認證',
    returnToTraining: '返回訓練',
    tierCertificationRibbons: '級別認證功能區',
    authenticationRequired: '需要認證',
    ladderCredentialExample: '階梯認證範例',
    certificationGuide: '認證指南',
    howLadderCertificationWorks: '階梯認證的運作方式',
    certificationExamInProgress: '認證考試進行中',
    admin: '管理員',
    studentHub: '學生中心',
    backToCertification: '返回認證',
    learnerIDInfo: '你的學習者ID:',
    certificationsCompleted: '已完成的認證',
    expertiseChallenges: '專業知識挑戰',
    masteryChallenges: '精通挑戰',
    tiersCertified: '認證的級別',
    certificationRecord: '認證記錄',
    noTopicsFound: '未找到主題。請嘗試其他搜尋。',
    selectEducationTier: '選擇教育級別',
    selectMasteryLevel: '選擇精通級別',
    availableInDuration: '可在',
    adultAccountRequired: '需要成人帳戶',
    completeYourAuthentication: '完成你的認證',
    verifyIdentityAndSetup: '驗證你的身份並設置你的認證認證，然後再繼續進行階梯的高級級別。',
    accountSetup: '帳戶設置',
    identityAssurance: '身份保証',
    confirmation: '確認',
    adultTiersRequireAccount: '成人教育級別(年輕成人、大學、勞動力、領導力)需要經過驗證的帳戶。登入現有帳戶或建立新帳戶。',
    emailUsername: '電子郵件 / 使用者名稱',
    password: '密碼',
    emailPlaceholder: 'name@example.com',
    passwordPlaceholder: '密碼',
    signIn: '登入',
    createAccount: '建立帳戶',
    identityAssuranceLevel: '身份保証級別',
    proctoringMode: '監考模式',
    chooseVerificationLevel: '選擇驗證級別...',
    chooseProctoringMethod: '選擇監考方法...',
    selectVerificationLevel: '選擇你想如何為此認證嘗試驗證身份。不同的級別對認證代表你的作品提供不同的保証。',
    confirmIdentity: '繼續表示你確認你將親自進行此認證嘗試，並且任何簽發的認證都將代表你的知識和技能。',
    confirmAttestion: '我確認我是進行此認證嘗試的人，任何簽發的認證都將代表我的工作和知識。',
    returnToCertification: '返回認證',
    cancel: '取消',
    findARungHelp: '搜尋與AI相關且令你感興趣的主題或課程。你可以開始學習主題或將其新增到你的路徑，而無需進行評估。',
    certificationHelp: '選擇你的教育級別和精通級別，然後進行認證評估。成人級別需要帳戶認證。',
    educationTierHelp: '選擇你的教育級別：學生(K-12)、年輕成人(18+)、大學、勞動力或領導力。',
    masteryLevelHelp: '選擇你的挑戰級別：認證(基本能力)、專業知識挑戰(進階)或精通挑戰(專家級綜合)。',
    identityAssuranceLevelHelp: '選擇你的身份驗證級別：自我證明(無檢查)、帳戶綁定(綁定到你的帳戶)、身份證明(簽名聲明)或監考人員驗證(身分證+活性+監考)。'
  }
};

export const LADDER_TIERS = [
  {
    id: 'tier-01',
    name: 'General AI Literacy',
    title: 'AI Orientation',
    accent: '#735f9e',
    vocabulary: ['artificial intelligence', 'machine learning', 'generative AI', 'model', 'chatbot', 'assistant', 'prompt', 'response', 'token', 'context', 'training data', 'inference', 'hallucination', 'multimodal', 'privacy'],
    topics: [
      'What artificial intelligence is and is not',
      'Traditional software vs AI systems',
      'Generative AI vs predictive AI',
      'Machine learning at a plain-language level',
      'Large language models at a plain-language level',
      'Chatbots, assistants, copilots, and agents',
      'Prompts, responses, and conversation turns',
      'Tokens and context windows',
      'Training data vs live information',
      'Hallucinations and why AI can be wrong',
      'AI strengths and weaknesses',
      'Common AI tool categories',
      'Multimodal AI basics',
      'Everyday AI use cases',
      'Basic privacy and sensitive data precautions',
      'Copyright and ownership awareness for beginners',
      'When not to use AI',
      'Beginner readiness check'
    ]
  },
  {
    id: 'tier-02',
    name: 'Chat Mastery',
    title: 'Prompting and Chatbot Fluency',
    accent: '#9a5fb0',
    vocabulary: ['system prompt', 'user prompt', 'role prompt', 'instruction', 'constraint', 'example', 'few-shot', 'output format', 'tone', 'persona', 'grounding', 'source', 'citation', 'follow-up', 'prompt template'],
    topics: [
      'Prompt anatomy',
      'Writing clear instructions',
      'Giving useful context',
      'Defining roles and personas',
      'Setting goals and success criteria',
      'Asking for specific output formats',
      'Using examples in prompts',
      'Prompt iteration and refinement',
      'Follow-up questions',
      'Asking AI to ask clarifying questions',
      'Asking for assumptions',
      'Asking for alternatives',
      'Asking for risks and tradeoffs',
      'Prompting for tone and audience',
      'Prompting for step-by-step help',
      'Prompting for checklists',
      'Prompting for critique and revision',
      'Novice readiness check'
    ]
  },
  {
    id: 'tier-03',
    name: 'Information Fluency',
    title: 'Research, Study, and Information Literacy',
    accent: '#c9a05a',
    vocabulary: ['source', 'primary source', 'secondary source', 'citation', 'claim', 'evidence', 'summary', 'synthesis', 'literature review', 'fact-checking', 'recency', 'credibility', 'bias', 'media literacy', 'epistemic humility'],
    topics: [
      'Using AI to learn unfamiliar topics',
      'Asking AI for learning plans',
      'Asking AI to explain at different difficulty levels',
      'Socratic tutoring with AI',
      'Generating practice questions',
      'Explaining mistakes with AI',
      'Summarizing articles and documents',
      'Comparing sources',
      'Identifying claims and evidence',
      'Fact-checking AI answers',
      'Understanding citation quality',
      'Using AI for research outlines',
      'Using AI for literature reviews',
      'Detecting weak or fabricated references',
      'Recognizing bias in AI responses',
      'Using AI with search engines',
      'Personal knowledge capture with AI',
      'Capable learner readiness check'
    ]
  },
  {
    id: 'tier-04',
    name: 'Business Process Design',
    title: 'Productivity and Professional Workflows',
    accent: '#3f7cac',
    vocabulary: ['workflow', 'SOP', 'template', 'knowledge base', 'meeting note', 'action item', 'task extraction', 'summarization', 'transformation', 'classification', 'prioritization', 'decision support', 'dashboard', 'review loop', 'human-in-the-loop'],
    topics: [
      'AI-assisted email drafting',
      'AI-assisted meeting notes',
      'AI-assisted action item extraction',
      'AI-assisted calendar and planning workflows',
      'AI-assisted document drafting',
      'AI-assisted document review',
      'AI-assisted spreadsheets',
      'AI-assisted data cleanup',
      'AI-assisted slide decks',
      'AI-assisted decision memos',
      'AI-assisted brainstorming',
      'AI-assisted project planning',
      'AI-assisted task prioritization',
      'AI-assisted personal productivity systems',
      'AI-assisted team communication',
      'Reusable prompt libraries',
      'Human review checkpoints',
      'Knowledge worker readiness check'
    ]
  },
  {
    id: 'tier-05',
    name: 'Visual & Audio Creation',
    title: 'Multimodal, Media, and Content Creation',
    accent: '#c0384f',
    vocabulary: ['multimodal', 'image generation', 'video generation', 'text-to-speech', 'speech-to-text', 'transcription', 'style transfer', 'storyboard', 'scene', 'prompt weighting', 'seed', 'upscaling', 'masking', 'inpainting', 'synthetic media'],
    topics: [
      'Image understanding with AI',
      'Image generation fundamentals',
      'Image editing and inpainting',
      'Brand-safe image generation',
      'Video generation fundamentals',
      'Video editing with AI',
      'Storyboarding with AI',
      'Audio transcription',
      'Voice generation and text-to-speech',
      'Music generation',
      'Podcast production with AI',
      'Social content workflows',
      'Marketing content workflows',
      'Design assistant workflows',
      'Presentation design with AI',
      'Synthetic media disclosure',
      'Deepfake awareness',
      'Creative user readiness check'
    ]
  },
  {
    id: 'tier-06',
    name: 'Business Function Mastery',
    title: 'Function-Specific AI Use',
    accent: '#8a5cf6',
    vocabulary: ['use case', 'business process', 'ROI', 'customer journey', 'pipeline', 'segmentation', 'personalization', 'support ticket', 'knowledge article', 'HR screening', 'financial analysis', 'legal review', 'clinical decision support', 'domain risk', 'escalation'],
    topics: [
      'AI use-case discovery',
      'AI for marketing',
      'AI for sales',
      'AI for customer support',
      'AI for operations',
      'AI for finance and accounting',
      'AI for HR and recruiting',
      'AI for legal workflows',
      'AI for healthcare workflows',
      'AI for education workflows',
      'AI for nonprofits',
      'AI for small businesses',
      'AI for enterprise teams',
      'AI for ecommerce',
      'AI for real estate',
      'AI for government and civic services',
      'AI use-case risk screening',
      'Business practitioner readiness check'
    ]
  },
  {
    id: 'tier-07',
    name: 'Workflow Automation & Integration',
    title: 'No-Code, Automation, and Team Systems',
    accent: '#e6a817',
    vocabulary: ['automation', 'trigger', 'action', 'webhook', 'integration', 'connector', 'no-code', 'low-code', 'custom assistant', 'custom GPT', 'workspace', 'permission', 'audit trail', 'approval step', 'escalation path', 'workflow owner'],
    topics: [
      'Workflow mapping for AI automation',
      'Repeated-task identification',
      'SOP design for AI-assisted work',
      'No-code automation basics',
      'Low-code automation basics',
      'Trigger and action design',
      'Webhook literacy',
      'Custom assistant design',
      'Custom GPT design',
      'Knowledge upload patterns',
      'Team prompt libraries',
      'Workspace permissions',
      'Approval and review flows',
      'Escalation flows',
      'Audit trails for AI workflows',
      'Change management for AI workflows',
      'Automation failure modes',
      'Workflow designer readiness check'
    ]
  },
  {
    id: 'tier-08',
    name: 'Application Development',
    title: 'APIs, Structured Outputs, and AI App Basics',
    accent: '#6b7fd7',
    vocabulary: ['API', 'SDK', 'endpoint', 'request', 'response', 'JSON', 'schema', 'structured output', 'function calling', 'tool calling', 'streaming', 'latency', 'rate limit', 'token cost', 'model provider', 'environment variable'],
    topics: [
      'AI API fundamentals',
      'Model provider comparison',
      'API authentication',
      'Request and response structure',
      'Prompt variables in applications',
      'System and developer instructions',
      'Structured outputs',
      'JSON schema for AI responses',
      'Function calling basics',
      'Tool calling basics',
      'Streaming response UX',
      'File inputs',
      'Image inputs',
      'Audio inputs',
      'Cost estimation',
      'Latency management',
      'Basic AI application architecture',
      'Applied builder readiness check'
    ]
  },
  {
    id: 'tier-09',
    name: 'Knowledge Systems & Retrieval',
    title: 'Data, Embeddings, Search, and RAG',
    accent: '#9a5fb0',
    vocabulary: ['embedding', 'vector', 'vector database', 'semantic search', 'keyword search', 'hybrid search', 'chunking', 'metadata', 'retrieval', 'reranking', 'RAG', 'grounding', 'citation', 'corpus', 'index', 'knowledge graph'],
    topics: [
      'Embeddings basics',
      'Vector search basics',
      'Vector database options',
      'Keyword search vs semantic search',
      'Hybrid search',
      'Document ingestion',
      'Chunking strategies',
      'Metadata design',
      'Retrieval-augmented generation',
      'Grounded answers',
      'Citation design',
      'Reranking',
      'Knowledge base design',
      'Knowledge graph integration',
      'Data freshness',
      'Retrieval evaluation',
      'Enterprise search architecture',
      'Knowledge systems builder readiness check'
    ]
  },
  {
    id: 'tier-10',
    name: 'Agentic Systems & Orchestration',
    title: 'Agents, Tools, MCP, and Orchestration',
    accent: '#8a5cf6',
    vocabulary: ['agent', 'tool use', 'planning', 'orchestration', 'task loop', 'subagent', 'delegation', 'memory', 'state', 'trace', 'Model Context Protocol', 'MCP server', 'MCP client', 'tool permission', 'tool result', 'sandbox'],
    topics: [
      'Agent concepts',
      'AI workflow vs AI agent',
      'Tool-using agents',
      'Agent planning patterns',
      'Task decomposition',
      'State and memory',
      'Short-term memory patterns',
      'Long-term memory patterns',
      'Subagents',
      'Multi-agent coordination',
      'Agent orchestration frameworks',
      'Model Context Protocol basics',
      'MCP server design',
      'MCP client design',
      'Agent permissions',
      'Agent sandboxes',
      'Agent observability',
      'Agent builder readiness check'
    ]
  },
  {
    id: 'tier-11',
    name: 'System Reliability & Operations',
    title: 'Evaluation, Reliability, Deployment, and Operations',
    accent: '#577590',
    vocabulary: ['eval', 'benchmark', 'golden dataset', 'test set', 'regression', 'LLM-as-judge', 'rubric', 'trace', 'observability', 'monitoring', 'fallback', 'cache', 'deployment', 'throughput', 'SLA', 'incident'],
    topics: [
      'Evaluation fundamentals',
      'Golden dataset creation',
      'LLM-as-judge evaluation',
      'Human evaluation workflows',
      'Rubric design',
      'Error analysis',
      'Prompt versioning',
      'Model comparison',
      'Regression testing for AI apps',
      'Trace analysis',
      'Observability tooling',
      'Monitoring production AI systems',
      'Fallback strategies',
      'Caching strategies',
      'Deployment patterns',
      'Incident response for AI systems',
      'AI system lifecycle management',
      'AI engineer readiness check'
    ]
  },
  {
    id: 'tier-12',
    name: 'Security & Threat Mitigation',
    title: 'Security, Privacy, Abuse, and Red Teaming',
    accent: '#d8572a',
    vocabulary: ['prompt injection', 'indirect prompt injection', 'jailbreak', 'data exfiltration', 'sensitive information disclosure', 'model theft', 'supply chain', 'sandbox escape', 'overreliance', 'excessive agency', 'adversarial example', 'red team', 'threat model', 'abuse monitoring'],
    topics: [
      'AI threat modeling',
      'Prompt injection',
      'Indirect prompt injection',
      'Jailbreaks',
      'Sensitive information disclosure',
      'Data exfiltration through tools',
      'Insecure output handling',
      'Tool permission risks',
      'Excessive agency',
      'Model denial of service and unbounded consumption',
      'Model theft and extraction',
      'Training data poisoning',
      'Vector and embedding weaknesses',
      'Supply chain risks in AI systems',
      'Red teaming AI applications',
      'Abuse monitoring',
      'Secure AI deployment checklists',
      'AI security practitioner readiness check'
    ]
  },
  {
    id: 'tier-13',
    name: 'Legal, Ethics & Compliance',
    title: 'Law, Ethics, Policy, and Compliance',
    accent: '#2d6a4f',
    vocabulary: ['governance', 'ethics', 'responsible AI', 'transparency', 'explainability', 'fairness', 'bias', 'accountability', 'auditability', 'privacy', 'consent', 'copyright', 'intellectual property', 'high-risk AI', 'GPAI', 'AI management system'],
    topics: [
      'Responsible AI fundamentals',
      'AI ethics frameworks',
      'Bias and fairness',
      'Explainability and interpretability',
      'Transparency and disclosure',
      'Human oversight',
      'Privacy law basics for AI use',
      'Data protection and consent',
      'Copyright and training data',
      'AI-generated content ownership',
      'Workplace AI policy',
      'Education and academic integrity',
      'Vendor risk management',
      'NIST AI Risk Management Framework',
      'ISO/IEC 42001 AI management systems',
      'EU AI Act basics',
      'Sector-specific AI compliance',
      'AI governance practitioner readiness check'
    ]
  },
  {
    id: 'tier-14',
    name: 'Model Science & Advanced Techniques',
    title: 'Model Science, ML, and Advanced AI Domains',
    accent: '#b08968',
    vocabulary: ['neural network', 'deep learning', 'transformer', 'attention', 'pretraining', 'post-training', 'fine-tuning', 'reinforcement learning', 'diffusion', 'classifier', 'recommender', 'time series', 'computer vision', 'speech model', 'robotics', 'MLOps'],
    topics: [
      'Machine learning fundamentals',
      'Supervised learning',
      'Unsupervised learning',
      'Deep learning fundamentals',
      'Transformer architecture',
      'Attention mechanisms',
      'Pretraining',
      'Post-training',
      'Fine-tuning',
      'Synthetic data',
      'Dataset quality',
      'Diffusion models',
      'Computer vision',
      'Speech AI',
      'Recommendation systems',
      'Forecasting and time series',
      'Reinforcement learning and robotics',
      'AI specialist readiness check'
    ]
  },
  {
    id: 'tier-15',
    name: 'Strategic Planning & Adoption',
    title: 'Product, Market, Adoption, and Frontier Planning',
    accent: '#735f9e',
    vocabulary: ['AI strategy', 'adoption roadmap', 'operating model', 'capability map', 'build vs buy', 'product moat', 'unit economics', 'adoption metric', 'change management', 'frontier model', 'alignment', 'interpretability', 'capability evaluation', 'regulatory monitoring', 'market map'],
    topics: [
      'AI strategy fundamentals',
      'AI opportunity discovery',
      'Use-case prioritization',
      'Build vs buy decisions',
      'AI vendor evaluation',
      'AI product management',
      'AI UX strategy',
      'AI business model design',
      'AI adoption roadmaps',
      'Team enablement programs',
      'Measuring AI adoption',
      'AI operating models',
      'AI market mapping',
      'Frontier AI capability tracking',
      'Interpretability and alignment awareness',
      'Regulatory monitoring',
      'Future-of-work planning',
      'AI strategist readiness check'
    ]
  }
].map((tier, tierIndex) => ({
  ...tier,
  order: tierIndex + 1,
  topics: tier.topics.map((title, topicIndex) => ({
    id: `T${String(tierIndex + 1).padStart(2, '0')}-L${String(topicIndex + 1).padStart(2, '0')}`,
    title,
    tierId: tier.id,
    order: topicIndex + 1
  }))
}));

export const DEFAULT_RESOURCES = [
  {
    type: 'official docs',
    label: 'OpenAI Agents Guide',
    url: 'https://platform.openai.com/docs/guides/agents',
    topicHints: ['agent', 'tool', 'orchestration', 'evaluation']
  },
  {
    type: 'official docs',
    label: 'Anthropic Model Context Protocol',
    url: 'https://docs.anthropic.com/en/docs/mcp',
    topicHints: ['MCP', 'tool', 'agent', 'context']
  },
  {
    type: 'official framework',
    label: 'NIST AI Risk Management Framework',
    url: 'https://www.nist.gov/itl/ai-risk-management-framework',
    topicHints: ['governance', 'risk', 'responsible', 'policy']
  },
  {
    type: 'official security',
    label: 'OWASP Top 10 for LLM Applications',
    url: 'https://owasp.org/www-project-top-10-for-large-language-model-applications/',
    topicHints: ['security', 'prompt injection', 'red team', 'abuse']
  },
  {
    type: 'official law',
    label: 'EU AI Act Overview',
    url: 'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai',
    topicHints: ['law', 'compliance', 'governance', 'EU AI Act']
  },
  {
    type: 'official course',
    label: 'Anthropic Academy',
    url: 'https://anthropic.skilljar.com/',
    topicHints: ['Claude', 'AI fluency', 'MCP', 'API']
  }
];
